## Some math in python

Complete the code in the functions math1-math12 below.


In [3]:
import numpy as np


In [16]:
def math1(mat):
    """
    Square each value in mat separatly and return the result
    """
    new_mat = np.zeros_like(mat)
    i,j = mat.shape
    print(i,j)
    print(new_mat)
    print(range(4))
    for num_i in range(i):
        for num_j in range(j):
            a = mat[num_i][num_j]
            new_mat[num_i][num_j] = a**2 
            
            
    return new_mat

In [17]:
mat = np.arange(16).reshape((4, 4))
print(math1(mat))

4 4
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
range(0, 4)
[[  0   1   4   9]
 [ 16  25  36  49]
 [ 64  81 100 121]
 [144 169 196 225]]


### Expected output  
[[  0   1   4   9]
 [ 16  25  36  49]
 [ 64  81 100 121]
 [144 169 196 225]]


In [18]:
def math2(mat):
    """
    Return the sum of all the values in mat
    """
    i,j = mat.shape
    sum = 0
    for num_i in range(i):
        for num_j in range(j):
            sum += mat[num_i][num_j]
        
    return sum


In [19]:
mat = np.arange(16).reshape((4, 4))
print(math2(mat))

120


### Expected output

120


In [20]:
def math3(mat):
    """
    Return the sum of each row in mat
    """
    i,j = mat.shape
    sum = np.zeros(i)
    for num_i in range(i):
        sum[num_i] = np.sum(mat[num_i,:])
    return sum

In [21]:
mat = np.arange(16).reshape((4, 4))
print(math3(mat)) 

[ 6. 22. 38. 54.]


### Expected output

[ 6 22 38 54]

In [24]:
def math4(mat):
    """
    Return a scaled version of mat, so that it sums to 1
    """
    fac = np.sum(mat)
    return mat/fac


In [25]:
mat = np.arange(16).reshape((4, 4))
print(math4(mat))

[[0.         0.00833333 0.01666667 0.025     ]
 [0.03333333 0.04166667 0.05       0.05833333]
 [0.06666667 0.075      0.08333333 0.09166667]
 [0.1        0.10833333 0.11666667 0.125     ]]


### Expected output

[[ 0.          0.00833333  0.01666667  0.025     ]
 [ 0.03333333  0.04166667  0.05        0.05833333]
 [ 0.06666667  0.075       0.08333333  0.09166667]
 [ 0.1         0.10833333  0.11666667  0.125     ]]

In [26]:
def math5(mat, v):
    """
    Element-wise multiply each column in mat with vector v
    """
    new_mat = np.zeros_like(mat)
    i,j = mat.shape
    
    for num_j in range(j):
        new_mat[:,num_j] = np.multiply(mat[:,num_j],v)
    return new_mat

In [27]:
mat = np.arange(16).reshape((4, 4))
vec = np.arange(4)
print(math5(mat,vec))

[[ 0  0  0  0]
 [ 4  5  6  7]
 [16 18 20 22]
 [36 39 42 45]]


### Expected output

[[ 0  0  0  0]
 [ 4  5  6  7]
 [16 18 20 22]
 [36 39 42 45]]

In [28]:
def math6(mat, v):
    """
    Element-wise multiply each row in mat with vector v
    """
    new_mat = np.zeros_like(mat)
    i,j = mat.shape
    
    for num_i in range(j):
        new_mat[num_i,:] = np.multiply(mat[num_i,:],v)
    return new_mat


In [29]:
mat = np.arange(16).reshape((4, 4))
vec = np.arange(4)
print(math6(mat,vec))

[[ 0  1  4  9]
 [ 0  5 12 21]
 [ 0  9 20 33]
 [ 0 13 28 45]]


### Expected output

[[ 0  1  4  9]
 [ 0  5 12 21]
 [ 0  9 20 33]
 [ 0 13 28 45]]

In [30]:

def math7(mat, v):
    """
    Matrix multiply matrix m with vector v
    """
    a = mat @ v
    return a

In [31]:
mat = np.arange(16).reshape((4, 4))
vec = np.arange(4)
print(math7(mat,vec))

[14 38 62 86]


### Expected output

[14 38 62 86]

In [34]:
def math8(mat):
    """
    Return the inverse matrix of mat
    """
    a = np.linalg.inv(mat)
    return a


In [35]:
mat = np.array([[4, 7], [2, 6]])
print(math8(mat))

[[ 0.6 -0.7]
 [-0.2  0.4]]


### Expected output

[[ 0.6 -0.7]
 [-0.2  0.4]]
 

In [36]:
def math9(mat, v):
    """
    Return the dot-product between each row in mat and v
    """
    a = mat @ v
    return a

In [37]:
mat = np.arange(16).reshape((4, 4))
vec = np.arange(4)
print(math9(mat,vec))

[14 38 62 86]


### Expected output

[14 38 62 86]

In [50]:
def math10(mat, v):
    """
    Return the dot-product between each column in mat and v
    """
    i,j = mat.shape
    print(j)
    new_mat = np.zeros(j)
    print(new_mat.shape)
    for num_j in range(j):
        new_mat[num_j] = mat[:,num_j] @ v
    return new_mat


In [51]:
mat = np.arange(16).reshape((4, 4))
vec = np.arange(4)
print(math10(mat,vec))

4
(4,)
[56. 62. 68. 74.]


### Expected output

[56 62 68 74]

In [52]:
def math11(mat1, mat2):
    """
    Return the dot-products between each corresponding (same index) column in mat1 and mat2
    """
    i,j = mat1.shape
    n,m = mat2.shape
    res = np.zeros(i)
    for num_i in range(i):
        res[num_i] = mat1[:,num_i] @ mat2[:,num_i]
    return res

In [53]:
mat = np.arange(16).reshape((4, 4))
print(math11(mat,mat.T))

[ 56. 174. 324. 506.]


### Expected value

[ 56 174 324 506]